config/routes.rb
Sticker::Application.routes.draw do

  resources :carts do
    collection do
      get 'home'
      get 'destroy_cart_item'
      get 'cancel_carts'
    end
    member do
      get 'cancel'
      get 'finish'
    end
  end
  # You can have the root of your site routed with "root"
  root to: 'carts#home'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

  resources :pictures do
    member do
      get 'add_to_cart'
    end
  end
  resources :devices do
    collection do
      get 'home'
    end
    member do
      get 'categories'
      get 'images'
    end
  end
  resources :categories
  resources :makers

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base

  has_many :cart_items

  extend Enumerize
  enumerize :stats, in: [:aberto, :concluido, :cancelado], predicates: true, default: :aberto

  def total
    cart_items.sum(:price)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy, :cancel,:finish]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    render layout: 'empty'
  end

  def finish
    #@cart.cart_items.each do |item|
      #system("lpr",item.picture.photo.url)
    #end
    system("lpr",@cart.cart_items.last.picture.photo.path)
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  def home
    render layout: 'empty'
  end

  def destroy_cart_item
    @cart_item = CartItem.find(params[:id_cart_item])
    @cart_item.delete
    redirect_to @cart_item.cart, notice: "Item removido."
  end

  def cancel_carts
    Cart.where(status: :aberto).update_all(status: :cancelado)
    #redirect_to home_carts_path
    render js: "window.location = '/carts/home'"
  end

  def cancel
    @cart.update(status: :cancelado)
    redirect_to home_carts_path
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:status)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/home.html.erb
<!--<div class="row" >
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <center>

    </center>
  </div>
  <div class="col-md-3"></div>
</div>-->

<%= link_to home_devices_path do %>
    <button type="button" style="position:absolute;top: 50%;left: 50%;width: 300px;height: 100px;margin-top:-50px;margin-left: -150px" class="btn btn-primary btn-lg dim">Iniciar    <i class="fa fa-play"></i></button>
<% end %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.status %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="wrapper wrapper-content animated fadeInRight">



  <div class="row">
    <div class="col-md-9">

      <div class="ibox">
        <div class="ibox-title">
          <span class="pull-right">(<strong><%= @cart.cart_items.count %></strong>) itens</span>
          <h5>Itens no carrinho</h5>
        </div>
        <% @cart.cart_items.each do |item| %>
          <div class="ibox-content">


            <div class="table-responsive">
              <table class="table shoping-cart-table">

                <tbody>
                <tr>
                  <td width="90">
                    <div class="cart-product-imitation" style="background-image: url(<%= item.picture.photo %>); background-size: 80px 80px; background-repeat: no-repeat;">

                    </div>
                  </td>
                  <td class="desc">
                    <h3>
                      <a href="#" class="text-navy">
                        <%= item.picture %>
                      </a>
                    </h3>
                    <p class="small">
                      <%= item.picture.category %>
                    </p>
                    <dl class="small m-b-none">
                      <dt><%= item.picture.device %></dt>
                      <!--<dd>A description list is perfect for defining terms.</dd>-->
                    </dl>

                    <!--<div class="m-t-sm">
                      <a href="#" class="text-muted"><i class="fa fa-gift"></i> Add gift package</a>
                      |
                      <a href="#" class="text-muted"><i class="fa fa-trash"></i> Remove item</a>
                    </div>-->
                  </td>

                  <td>
                    <!--$180,00
                    <s class="small text-muted">$230,00</s>-->
                  </td>
                  <td width="65">
                    <!--<input type="text" class="form-control" placeholder="1">-->
                    <%= link_to destroy_cart_item_carts_path(id_cart_item: item.id), method: :delete do %>
                        <i class="fa fa-trash fa-2x"></i>
                    <% end %>
                  </td>
                  <td>
                    <h4>
                      <%= number_to_currency(item.price,unit: "R$ ") %>
                    </h4>
                  </td>
                </tr>
                </tbody>
              </table>
            </div>

          </div>
        <% end %>


        <div class="ibox-content">

          <%= link_to finish_cart_path(@cart) do %>
            <button class="btn btn-primary pull-right"><i class="fa fa fa-shopping-cart"></i> Finalizar Compra</button>
          <% end %>
          <%= link_to home_devices_path do %>
            <button class="btn btn-white"><i class="fa fa-arrow-left"></i> Continuar comprando</button>
          <% end %>

        </div>
      </div>

    </div>
    <div class="col-md-3">

      <div class="ibox">
        <div class="ibox-title">
          <h5>Total</h5>
        </div>
        <div class="ibox-content">
                            <span>
                                Total
                            </span>
          <h2 class="font-bold">
            <%= number_to_currency(@cart.total,unit: "R$ ") %>
          </h2>

          <hr/>
          <span class="text-muted small">
                                <!--*For United States, France and Germany applicable sales tax will be applied-->
                            </span>
          <div class="m-t-sm">
            <div class="btn-group">
              <a href="<%= finish_cart_path(@cart) %>" class="btn btn-primary btn-sm"><i class="fa fa-shopping-cart"></i>Finalizar</a>
              <a href="<%= cancel_cart_path(@cart) %>" class="btn btn-white btn-sm"> Cancelar</a>
            </div>
          </div>
        </div>
      </div>

     <!-- <div class="ibox">
        <div class="ibox-title">
          <h5>Support</h5>
        </div>
        <div class="ibox-content text-center">



          <h3><i class="fa fa-phone"></i> +43 100 783 001</h3>
          <span class="small">
                                Please contact with us if you have any questions. We are avalible 24h.
                            </span>


        </div>
      </div>-->

      <!--<div class="ibox">
        <div class="ibox-content">

          <p class="font-bold">
            Other products you may be interested
          </p>

          <hr/>
          <div>
            <a href="#" class="product-name"> Product 1</a>
            <div class="small m-t-xs">
              Many desktop publishing packages and web page editors now.
            </div>
            <div class="m-t text-righ">

              <a href="#" class="btn btn-xs btn-outline btn-primary">Info <i class="fa fa-long-arrow-right"></i> </a>
            </div>
          </div>
          <hr/>
          <div>
            <a href="#" class="product-name"> Product 2</a>
            <div class="small m-t-xs">
              Many desktop publishing packages and web page editors now.
            </div>
            <div class="m-t text-righ">

              <a href="#" class="btn btn-xs btn-outline btn-primary">Info <i class="fa fa-long-arrow-right"></i> </a>
            </div>
          </div>

        </div>
      </div>-->

    </div>
  </div>




</div>