config/routes.rb
Sticker::Application.routes.draw do

  resources :carts do
    collection do
      get 'home'
      get 'destroy_cart_item'
      get 'cancel_carts'
    end
    member do
      get 'cancel'
      get 'finish'
    end
  end
  # You can have the root of your site routed with "root"
  root to: 'carts#home'

  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

  resources :pictures do
    member do
      get 'add_to_cart'
    end
  end
  resources :devices do
    collection do
      get 'home'
    end
    member do
      get 'categories'
      get 'images'
    end
  end
  resources :categories
  resources :makers

end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id          :integer          not null, primary key
#  name        :string
#  photo       :string
#  price       :decimal(, )
#  category_id :integer
#  device_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image_real  :string
#
# Indexes
#
#  index_pictures_on_category_id  (category_id)
#  index_pictures_on_device_id    (device_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (device_id => devices.id)
#

class Picture < ActiveRecord::Base
  belongs_to :category
  belongs_to :device

  validates :name, :photo, :price, :category_id, :device_id, presence: true

  mount_uploader :photo, AvatarUploader
  mount_uploader :image_real, AvatarUploader

  def to_s
    self.name
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy,:add_to_cart]
  before_action :set_combos, only: [:new,:create,:edit,:update]
  protect_from_forgery except: :add_to_cart


  # GET /pictures
  # GET /pictures.json
  def index
    @q = Picture.search(params[:q])
    @pictures = @q.result.page(params[:page]).per(20)
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  def add_to_cart
    @cart = Cart.where(status: :aberto).last
    if !@cart
      @cart = Cart.create(status: :aberto)
    end
    @cart_item = CartItem.create(cart: @cart, picture: @picture,quantity: 1,price: @picture.price)

    respond_to do |format|
      format.html {redirect_to images_device_path(id: @picture.device.id,category: @picture.category.id), notice: "Produto adicionado com sucesso."}
    end
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to pictures_path, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to pictures_path, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

  def set_combos
    @categories = Category.all.map{|a| [a.name,a.id]}
    @devices = Device.all.map{|a| [a.name,a.id]}
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :photo, :price, :category_id, :device_id,:image_real)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(picture) do |f| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
    <br>
<div class="row">
  <div class="field col-md-6">
    <% if f.object.photo.present? %>
      <img src="<%= f.object.photo %>"/><br>
    <% end %>
    <%= f.label :photo, "Preview" %>
    <%= f.file_field :photo, class:"form-control" %>
  </div>

    <div class="field col-md-6">
      <% if f.object.image_real.present? %>
          <img src="<%= f.object.image_real %>"/><br>
      <% end %>
      <%= f.label :image_real, "Imagem" %>
      <%= f.file_field :image_real, class:"form-control" %>
    </div>
</div>
  <div class="field">
    <%= f.label :price, "Preço" %>
    <%= f.text_field :price , class:"form-control"%>
  </div>

  <div class="field">
    <%= f.label :category_id, "Categoria" %>
    <%= f.select :category_id, @categories,{prompt:true}, class:"form-control" %>
  </div>

  <div class="field">
    <%= f.label :device_id, "Aparelho" %>
    <%= f.select :device_id, @devices,{prompt:true }, class:"form-control"%>
  </div>
    <br>

  <div class="actions">
    <%= f.submit "Salvar",class:"btn btn-w-m btn-primary" %>
  </div>
    <br>
<% end %>

app/views/pictures/add_to_cart.js.erb
swal( "Good job!", "You clicked the button!", "success");

app/views/pictures/edit.html.erb
<h1>Editando Adesivo</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Visualizar', @picture %> |
<%= link_to 'Voltar', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adesivos</h1>

<!--<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Preço</th>
      <th>Categoria</th>
      <th>Aparelho</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @pictures.each do |picture| %>
      <tr>
        <td><%#= picture.name %></td>
        <td><%#= picture.price %></td>
        <td><%#= picture.category %></td>
        <td><%#= picture.device %></td>
        <td><%#= link_to 'Show', picture %></td>
        <td><%#= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%#= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>-->

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins collapsed">
      <div class="ibox-title">
        <h5>Pesquisa</h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>

        </div>
      </div>
      <div class="ibox-content">
        <%= search_form_for(@q, url: pictures_path) do |f| %>
            <%= f.text_field :name_or_category_name_or_device_name_cont, class: "form-control", placeholder: "Imagem, Categoria ou Aparelho" %>
            <br>
            <%= f.select :device_id_eq, Device.all.map{|d| [d.name,d.id]},{prompt: "Aparelho"},{ class:"form-control"} %>
            <br>
            <%= f.select :category_id_eq, Category.all.map{|d| [d.name,d.id]},{prompt: "Categoria"},{ class:"form-control"} %>
            <br>
            <%= f.submit "Pesquisar", class: "btn btn-w-m btn-primary" %>
            <%= link_to "Limpar", pictures_path, class: "btn btn-w-m btn-primary" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
  <% @pictures.each do |picture| %>
        <%= link_to edit_picture_path(picture) do %>
          <div class="col-lg-3">
            <div class="widget yellw-bg no-padding" >
              <div class="flot-chart" style="background-image: url(<%= picture.photo %>);  background-repeat: no-repeat;">
                <div class="flot-chart-content" id="flot-chart3"></div>
              </div>
              <div class="p-m">
                <h1 class="m-xs"><%= number_to_currency(picture.price,unit: "R$ ") %></h1>

                <h3 class="font-bold no-margins">
                  <%= picture %>
                </h3>
                <small><%= picture.category %> - <%= picture.device %></small>
              </div>

            </div>
          </div>
        <% end %>
  <% end %>
  </div>
</div>

<%= paginate @pictures %>


<br>

<%= link_to 'Novo Adesivo', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @picture.photo %>
</p>

<p>
  <strong>Price:</strong>
  <%= @picture.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @picture.category %>
</p>

<p>
  <strong>Device:</strong>
  <%= @picture.device %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>